install(TARGETS ${PROJECT_NAME}
   RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR}
)

set(AUND_CONFIG_DIR "${CMAKE_INSTALL_PREFIX}/etc")
set(AUND_CONFIG "${AUND_CONFIG_DIR}/aund.conf")

install(FILES ${CMAKE_CURRENT_SOURCE_DIR}/aund.conf.5 DESTINATION ${CMAKE_INSTALL_PREFIX}/man/man5)
install(FILES ${CMAKE_CURRENT_SOURCE_DIR}/aund.passwd.5 DESTINATION ${CMAKE_INSTALL_PREFIX}/man/man5)
install(FILES ${CMAKE_CURRENT_SOURCE_DIR}/aund.8 DESTINATION ${CMAKE_INSTALL_PREFIX}/man/man8)
install(FILES ${CMAKE_CURRENT_SOURCE_DIR}/aund.conf DESTINATION ${AUND_CONFIG_DIR})

